name: Publish package to the RubyGems.org
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release. v prefix is required (e.g. v1.10.0)'
        required: true

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3
      - name: Update version file with the release version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.version }}
          else
            VERSION=${{ github.event.release.tag_name }}
          fi
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          sed -i "s/VERSION = \".*\"/VERSION = \"$VERSION\"/" lib/line/bot/api/version.rb
          
          cat lib/line/bot/api/version.rb
          
          # commit
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add lib/line/bot/api/version.rb
          git commit -m "Set version to $VERSION"
      - uses: rubygems/release-gem@v1

      - name: Create GitHub Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const version = process.env.VERSION;
            const issueTitle = `Release job for ${version} failed`;
            const issueBody = `The release job failed. Please check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.`;
            const assignees = [context.actor];
            await github.rest.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody,
              assignees
            });
